INSERT INTO SICs (D_SICHeadersGroupCode, sSICCode, sSICDescription, mReturnRate, bRateIndicator, bAcceptForm, isActive) VALUES
('119', 100, 'Agricultural Production - Crops', NULL, NULL, NULL, NULL),
('119', 200, 'Agricultural Production - Livestock', NULL, NULL, NULL, NULL),
('119', 700, 'Other Agricultural Services (crop spraying, planting)', NULL, NULL, NULL, NULL),
('119', 740, 'Veterinary Services', NULL, NULL, NULL, NULL),
('114', 750, 'Automobile Rentals', NULL, NULL, NULL, NULL),
('119', 751, 'Livestock Services', NULL, NULL, NULL, NULL),
('119', 752, 'Animal Specialty Services (boarding, kennels, grooming, etc.)', NULL, NULL, NULL, NULL),
('119', 780, 'Landscaping, Lawn and Garden Services', NULL, NULL, NULL, NULL),
('119', 800, 'Forestry (wood cutting)', NULL, NULL, NULL, NULL),
('119', 801, 'Snow Removal', NULL, NULL, NULL, NULL),
('119', 900, 'Fishing, Hunting and Trapping', NULL, NULL, NULL, NULL),
('121', 1500, 'General Building Contractors', NULL, NULL, NULL, NULL),
('121', 1501, 'Building Contractor - Remodeling and Repairs', NULL, NULL, NULL, NULL),
('121', 1520, 'Interior Finishing, Partition Retail/Desig', NULL, NULL, NULL, NULL),
('121', 1540, 'Industrial Bldgs/Designers/Installation and Equipment/Elevators', NULL, NULL, NULL, NULL),
('121', 1550, 'Sewage Treatment Plant/Non-Residential Bldg/Store', NULL, NULL, NULL, NULL),
('121', 1600, 'Heavy Construction (except building)', NULL, NULL, NULL, NULL),
('121', 1610, 'Highway/Paving Parking Area/Sealers Improvement/Maintenance', NULL, NULL, NULL, NULL),
('121', 1620, 'Bridge/Tunnel/Pipeline/Gas Line Maintenance & Repair', NULL, NULL, NULL, NULL),
('121', 1630, 'Telephone/Television Cable/Fiber Optic Underground', NULL, NULL, NULL, NULL),
('121', 1700, 'Power Plant/Railroad/Drain Layout/Golf Course/Erosion Control', NULL, NULL, NULL, NULL),
('121', 1701, 'Plumbing and Heating Contractors', NULL, NULL, NULL, NULL),
('121', 1710, 'Other Special Trades Furnace/Gas Burners/Humidifying Equipment/Air Pollutio', NULL, NULL, NULL, NULL),
('121', 1720, 'Plumbing Services - Piping/Septic Tank Systems/Repair, etc.', NULL, NULL, NULL, NULL),
('121', 1730, 'Air Conditioning Systems/Cooling Towers/Ventilating Ducting/Refrigeration Equipment', NULL, NULL, NULL, NULL),
('121', 1740, 'Painting Comm./Industrial/All Types Painting', NULL, NULL, NULL, NULL),
('121', 1742, 'Plastering Drywall and Acoustical Work Installation, Radiant Barrier Contracts', NULL, NULL, NULL, NULL),
('121', 1745, 'Masonry Stone/Brick Work/Bldg Concrete', NULL, NULL, NULL, NULL),
('121', 1750, 'Electric Contractors/Lighting/Electronic Con Systems/Computer Cabling, etc. ', NULL, NULL, NULL, NULL),
('108', 2000, 'Food and Kindred Products', NULL, NULL, NULL, NULL),
('108', 2200, 'Textile Mill Products (yarn, thread, fabrics)', NULL, NULL, NULL, NULL),
('108', 2300, 'Apparel and Other Textile Products', NULL, NULL, NULL, NULL),
('108', 2400, 'Lumber and Wood Products 7040 Lodging Places - not listed above', NULL, NULL, NULL, NULL),
('108', 2500, 'Furniture and Fixtures', NULL, NULL, NULL, NULL),
('108', 2600, 'Paper and Related Products', NULL, NULL, NULL, NULL),
('108', 2700, 'Printing and Publishing', NULL, NULL, NULL, NULL),
('108', 2800, 'Chemicals and Related Products', NULL, NULL, NULL, NULL),
('108', 2900, 'Petroleum and Coal Products', NULL, NULL, NULL, NULL),
('108', 3000, 'Rubber and Plastics 7217 Carpet and Upholstery Cleaning', NULL, NULL, NULL, NULL),
('108', 3100, 'Leather and Leather Products', NULL, NULL, NULL, NULL),
('108', 3200, 'Stone, Clay and Glass Products', NULL, NULL, NULL, NULL),
('108', 3300, 'Primary Metals Industries (foundries, smelting)', NULL, NULL, NULL, NULL),
('108', 3400, 'Fabricated Metal Products', NULL, NULL, NULL, NULL),
('108', 3500, 'Industrial Machinery and Equipment', NULL, NULL, NULL, NULL),
('108', 3600, 'Electronic and Other Electronic Equipment', NULL, NULL, NULL, NULL),
('108', 3700, 'Transportation Equipment', NULL, NULL, NULL, NULL),
('108', 3800, 'Instruments and Related', NULL, NULL, NULL, NULL),
('108', 3900, 'Manufacturing Industries - not listed above', NULL, NULL, NULL, NULL),
('110', 4000, 'Railroad Transportatio', NULL, NULL, NULL, NULL),
('110', 4001, 'Local and Interurban Passenger Transit (including taxi and limousine services)', NULL, NULL, NULL, NULL),
('110', 4212, 'Local Trucking, Garbage Collection and Transportatio', NULL, NULL, NULL, NULL),
('110', 4213, 'Interstate Trucking', NULL, NULL, NULL, NULL),
('110', 4214, 'Courier Services', NULL, NULL, NULL, NULL),
('110', 4220, 'Warehouse and Storage', NULL, NULL, NULL, NULL),
('110', 4400, 'Water Transportatio', NULL, NULL, NULL, NULL),
('110', 4500, 'Air Transportatio', NULL, NULL, NULL, NULL),
('110', 4600, 'Pipelines (except natural gas)', NULL, NULL, NULL, NULL),
('110', 4700, 'Transportation, Travel and Tour Agencies', NULL, NULL, NULL, NULL),
('122', 4810, 'Telephone Communications', NULL, NULL, NULL, NULL),
('122', 4820, 'Telegraph and Other Communications', NULL, NULL, NULL, NULL),
('122', 4830, 'Radio and Television Broadcasting', NULL, NULL, NULL, NULL),
('122', 4840, 'Cable and Pay Televisio', NULL, NULL, NULL, NULL),
('122', 4890, 'Communications not listed above', NULL, NULL, NULL, NULL),
('122', 4910, 'Electric Services', NULL, NULL, NULL, NULL),
('122', 4920, 'Gas Production and Distributio', NULL, NULL, NULL, NULL),
('122', 4940, 'Water Supply', NULL, NULL, NULL, NULL),
('122', 4950, 'Sewage and Refuse Systems (landfills, Hazardous waste disposal, etc)', NULL, NULL, NULL, NULL),
('105', 5010, 'Motor Vehicle Parts and Supplies', NULL, NULL, NULL, NULL),
('105', 5020, 'Furniture and Home Furnishings', NULL, NULL, NULL, NULL),
('105', 5030, 'Lumber and Construction Materials', NULL, NULL, NULL, NULL),
('105', 5040, 'Professional, Commercial Equipment', NULL, NULL, NULL, NULL),
('105', 5050, 'Metals and Materials', NULL, NULL, NULL, NULL),
('105', 5060, 'Electrical Goods', NULL, NULL, NULL, NULL),
('105', 5070, 'Metals and Materials', NULL, NULL, NULL, NULL),
('105', 5080, 'Hardware, Plumbing and Heating Equipment', NULL, NULL, NULL, NULL),
('105', 5090, 'Durable Good - not listed above', NULL, NULL, NULL, NULL),
('105', 5110, 'Paper and Paper Products', NULL, NULL, NULL, NULL),
('105', 5120, 'Drug, Drug Proprieties and Sundries', NULL, NULL, NULL, NULL),
('105', 5130, 'Apparel, Piece Goods and Notions', NULL, NULL, NULL, NULL),
('105', 5140, 'Groceries and Related Products', NULL, NULL, NULL, NULL),
('105', 5150, 'Farm - Product Raw Materials', NULL, NULL, NULL, NULL),
('105', 5160, 'Chemicals and Allied Products', NULL, NULL, NULL, NULL),
('105', 5170, 'Petroleum and Petroleum Products', NULL, NULL, NULL, NULL),
('105', 5180, 'Alcoholic Beverages', NULL, NULL, NULL, NULL),
('105', 5190, 'Non-durable Goods - not listed above', NULL, NULL, NULL, NULL),
('106', 5211, 'Lumber and Other Building Materials', NULL, NULL, NULL, NULL),
('106', 5231, 'Paint, Glass and Wallpaper', NULL, NULL, NULL, NULL),
('106', 5251, 'Hardware', NULL, NULL, NULL, NULL),
('106', 5261, 'Retail Nurseries, Lawn and Garden Supplies', NULL, NULL, NULL, NULL),
('106', 5271, 'Mobile Home Dealers', NULL, NULL, NULL, NULL),
('106', 5272, 'Elevator Maintenance', NULL, NULL, NULL, NULL),
('106', 5283, 'Farm Machinery', NULL, NULL, NULL, NULL),
('107', 5300, 'Department and General Merchandise Stores', NULL, NULL, NULL, NULL),
('101', 5411, 'Grocery Stores', NULL, NULL, NULL, NULL),
('101', 5412, 'Soft Drinks', NULL, NULL, NULL, NULL),
('101', 5421, 'Meat and Fish', NULL, NULL, NULL, NULL),
('101', 5431, 'Fruits and Vegetables', NULL, NULL, NULL, NULL),
('101', 5441, 'Candy, Nuts and confectioneries', NULL, NULL, NULL, NULL),
('101', 5461, 'Retail Baked Goods', NULL, NULL, NULL, NULL),
('101', 5499, 'Misc. Food (dairy products, foods, etc.)', NULL, NULL, NULL, NULL),
('102', 5511, 'Car Dealers - New and Used', NULL, NULL, NULL, NULL),
('102', 5521, 'Car Dealers - Used', NULL, NULL, NULL, NULL),
('102', 5531, 'Auto and Home Supplies', NULL, NULL, NULL, NULL),
('102', 5541, 'Gasoline Service Stations', NULL, NULL, NULL, NULL),
('102', 5551, 'Boat Dealers', NULL, NULL, NULL, NULL),
('102', 5561, 'Recreational Vehicle Dealers', NULL, NULL, NULL, NULL),
('102', 5571, 'Motorcycle Dealers', NULL, NULL, NULL, NULL),
('102', 5599, 'Automotive Dealers - Not Listed Above', NULL, NULL, NULL, NULL),
('103', 5600, 'Clothing (men’s, women’s, children’s)', NULL, NULL, NULL, NULL),
('103', 5661, 'Shoes', NULL, NULL, NULL, NULL),
('103', 5669, 'Misc. Apparel and Accessories', NULL, NULL, NULL, NULL),
('104', 5712, 'Furniture', NULL, NULL, NULL, NULL),
('104', 5713, 'Floor Coverings', NULL, NULL, NULL, NULL),
('104', 5714, 'Drapery and Upholstery', NULL, NULL, NULL, NULL),
('104', 5719, 'Misc. Home Furnishings', NULL, NULL, NULL, NULL),
('104', 5722, 'Household Appliances', NULL, NULL, NULL, NULL),
('104', 5723, 'Drinking Water / Drinking Water Systems', NULL, NULL, NULL, NULL),
('104', 5731, 'Radio, TV and Electronics', NULL, NULL, NULL, NULL),
('104', 5734, 'Computer and Computer Software', NULL, NULL, NULL, NULL),
('104', 5735, 'Records and Pre-recorded Tapes', NULL, NULL, NULL, NULL),
('104', 5736, 'Musical Instruments', NULL, NULL, NULL, NULL),
('100', 5812, 'Eating Places (restaurants, concession stands, etc.)', NULL, NULL, NULL, NULL),
('100', 5813, 'Drinking Place (bars, taverns, nightclubs, etc.)', NULL, NULL, NULL, NULL),
('107', 5912, 'Drug Stores and Proprietary Stores', NULL, NULL, NULL, NULL),
('107', 5921, 'Liquor Stores', NULL, NULL, NULL, NULL),
('107', 5932, 'Used Merchandise (antiques, flea markets, health secondhand goods, etc.)', NULL, NULL, NULL, NULL),
('107', 5941, 'Sporting Goods and Bicycles', NULL, NULL, NULL, NULL),
('107', 5942, 'Books', NULL, NULL, NULL, NULL),
('107', 5943, 'Stationery', NULL, NULL, NULL, NULL),
('107', 5944, 'Jewelry', NULL, NULL, NULL, NULL),
('107', 5945, 'Hobbies, Toys and Games', NULL, NULL, NULL, NULL),
('107', 5946, 'Cameras and Photographic Supplies', NULL, NULL, NULL, NULL),
('107', 5947, 'Gifts, Novelties and Souvenirs', NULL, NULL, NULL, NULL),
('107', 5948, 'Luggage and Leather Goods', NULL, NULL, NULL, NULL),
('107', 5949, 'Sewing, Needlework and Piece Goods', NULL, NULL, NULL, NULL),
('107', 5950, 'Fireworks', NULL, NULL, NULL, NULL),
('107', 5961, 'Catalog and Mail Order', NULL, NULL, NULL, NULL),
('107', 5962, 'Vending Machines Operators', NULL, NULL, NULL, NULL),
('107', 5963, 'Direct Selling Business (telephone, door-to-door)', NULL, NULL, NULL, NULL),
('107', 5980, 'Fuel Dealers (oil, LP gas, coal, etc.)', NULL, NULL, NULL, NULL),
('107', 5992, 'Florists', NULL, NULL, NULL, NULL),
('107', 5993, 'Tobacco Stores and Stands', NULL, NULL, NULL, NULL),
('107', 5994, 'Newspaper, Magazine Dealers & Newsstands', NULL, NULL, NULL, NULL),
('107', 5998, 'Optical Goods', NULL, NULL, NULL, NULL),
('107', 5999, 'Misc. Retail (coin, pets, pet foods, silk flowers, hot tubs or any items not listed above)', NULL, NULL, NULL, NULL),
('109', 6000, 'Banks, Saving Institutions, Credit Unions', NULL, NULL, NULL, NULL),
('109', 6100, 'Credit Institutions, Mortgage Bankers, Brokers', NULL, NULL, NULL, NULL),
('109', 6141, 'Personal Credit Institutions', NULL, NULL, NULL, NULL),
('109', 6200, 'Security and Commodity Brokers', NULL, NULL, NULL, NULL),
('109', 6300, 'Insurance Carriers', NULL, NULL, NULL, NULL),
('109', 6400, 'Insurance Agents, Brokers and Service', NULL, NULL, NULL, NULL),
('109', 6500, 'Real Estate', NULL, NULL, NULL, NULL),
('109', 6700, 'Holding and Other Investment Offices', NULL, NULL, NULL, NULL),
('111', 7010, 'Hotels, Motels, Inns', NULL, NULL, NULL, NULL),
('111', 7012, 'Resorts', NULL, NULL, NULL, NULL),
('111', 7020, 'Rooming and Boarding Houses', NULL, NULL, NULL, NULL),
('111', 7030, 'Trailer Park and Camping Facilities', NULL, NULL, NULL, NULL),
('111', 7040, 'Lodging Places - not listed above', NULL, NULL, NULL, NULL),
('112', 7210, 'Laundry and Dry Cleaning Services', NULL, NULL, NULL, NULL),
('112', 7213, 'Linen Supply', NULL, NULL, NULL, NULL),
('112', 7215, 'Coin-Operated Laundries and Cleaning', NULL, NULL, NULL, NULL),
('112', 7217, 'Carpet and Upholstery Cleaning', NULL, NULL, NULL, NULL),
('112', 7219, 'Laundry and Garment Services - not listed above', NULL, NULL, NULL, NULL),
('112', 7220, 'Photographers and Photographic Studios (portrait)', NULL, NULL, NULL, NULL),
('112', 7230, 'Beauty Shop', NULL, NULL, NULL, NULL),
('112', 7240, 'Barber Shop', NULL, NULL, NULL, NULL),
('112', 7250, 'Shoe Repair and Shoe Shine Parlors', NULL, NULL, NULL, NULL),
('112', 7299, 'Personal Services - not listed above (sauna, massage parlors, dating services, funeral homes, etc.)', NULL, NULL, NULL, NULL),
('113', 7310, 'Advertising', NULL, NULL, NULL, NULL),
('113', 7320, 'Credit Reporting and Collectio', NULL, NULL, NULL, NULL),
('113', 7331, 'Direct Mail Advertising Services', NULL, NULL, NULL, NULL),
('113', 7334, 'Photocopying and Duplicating Services', NULL, NULL, NULL, NULL),
('113', 7335, 'Commercial Photography', NULL, NULL, NULL, NULL),
('113', 7336, 'Commercial Art and Graphic Desig', NULL, NULL, NULL, NULL),
('113', 7338, 'Secretarial and Court Reporting Services', NULL, NULL, NULL, NULL),
('113', 7342, 'Disinfecting and Pest Control Services', NULL, NULL, NULL, NULL),
('113', 7349, 'Building Maintenance Services', NULL, NULL, NULL, NULL),
('113', 7350, 'Misc. Equipment Rental and Leasing', NULL, NULL, NULL, NULL),
('113', 7360, 'Employment Agencies and Help Services', NULL, NULL, NULL, NULL),
('113', 7370, 'Computer Programming Date Processing and Related Services', NULL, NULL, NULL, NULL),
('113', 7377, 'Computer Rental and Leasing', NULL, NULL, NULL, NULL),
('113', 7381, 'Detective and Armored Car Services', NULL, NULL, NULL, NULL),
('113', 7382, 'Security System Services', NULL, NULL, NULL, NULL),
('113', 7384, 'Photofinishing Laboratories', NULL, NULL, NULL, NULL),
('114', 7520, 'Automotive Parking', NULL, NULL, NULL, NULL),
('114', 7530, 'Automotive Repair Shops', NULL, NULL, NULL, NULL),
('114', 7542, 'Car Washes', NULL, NULL, NULL, NULL),
('114', 7549, 'Automotive Services - not listed above (towing, rustproofing)', NULL, NULL, NULL, NULL),
('115', 7620, 'Electrical Repair Shops (radio, TV, Appliances, etc.)', NULL, NULL, NULL, NULL),
('115', 7630, 'Watch, Clock and Jewelry Repair', NULL, NULL, NULL, NULL),
('115', 7640, 'Upholstery and Furniture Repair', NULL, NULL, NULL, NULL),
('115', 7650, 'Shoe Repair and Shoe Shining Parlors', NULL, NULL, NULL, NULL),
('115', 7690, 'Small Engine Repair', NULL, NULL, NULL, NULL),
('115', 7691, 'Miscellaneous Repair Shops', NULL, NULL, NULL, NULL),
('115', 7693, 'Repair and Refill Services', NULL, NULL, NULL, NULL),
('116', 7810, 'Movie Production and Distribution Services', NULL, NULL, NULL, NULL),
('116', 7830, 'Movie Theaters', NULL, NULL, NULL, NULL),
('116', 7840, 'Video Tape Rental', NULL, NULL, NULL, NULL),
('116', 7910, 'Dance Studios, Schools and Halls', NULL, NULL, NULL, NULL),
('116', 7920, 'Producers, Orchestras, Entertainers', NULL, NULL, NULL, NULL),
('116', 7930, 'Bowling Centers', NULL, NULL, NULL, NULL),
('116', 7940, 'Commercial Sports', NULL, NULL, NULL, NULL),
('116', 7991, 'Physical Fitness Facilities', NULL, NULL, NULL, NULL),
('116', 7992, 'Public Golf Courses', NULL, NULL, NULL, NULL),
('116', 7993, 'Coin Operated Amusement Devices', NULL, NULL, NULL, NULL),
('116', 7999, 'Amusements - not listed above', NULL, NULL, NULL, NULL),
('117', 8010, 'Offices and Clinics of Medical Doctors Elevators', NULL, NULL, NULL, NULL),
('117', 8020, 'Offices and Clinics of Dentists', NULL, NULL, NULL, NULL),
('117', 8040, 'Office of Other Health Practitioner (chiropractors, optometrists, podiatrists, acupuncture, etc.)', NULL, NULL, NULL, NULL),
('117', 8050, 'Nursing and Personal Care Facilities', NULL, NULL, NULL, NULL),
('117', 8060, 'Hospitals Maintenance', NULL, NULL, NULL, NULL),
('117', 8070, 'Medical and Dental Laboratories', NULL, NULL, NULL, NULL),
('117', 8080, 'Home Health Care Services', NULL, NULL, NULL, NULL),
('117', 8090, 'Health Services - not listed above', NULL, NULL, NULL, NULL),
('123', 8110, 'Legal Services', NULL, NULL, NULL, NULL),
('118', 8210, 'Elementary and Secondary Schools', NULL, NULL, NULL, NULL),
('118', 8220, 'College and Universities', NULL, NULL, NULL, NULL),
('118', 8230, 'Libraries', NULL, NULL, NULL, NULL),
('118', 8240, 'Vocational Schools', NULL, NULL, NULL, NULL),
('118', 8290, 'Schools and Educational Services - not listed above', NULL, NULL, NULL, NULL),
('118', 8320, 'Individual and Family Services (including counseling)', NULL, NULL, NULL, NULL),
('118', 8330, 'Job Training and Related Services', NULL, NULL, NULL, NULL),
('118', 8350, 'Child Day Care Services', NULL, NULL, NULL, NULL),
('118', 8360, 'Residential Care', NULL, NULL, NULL, NULL),
('118', 8390, 'Social Services - not listed above', NULL, NULL, NULL, NULL),
('116', 8410, 'Museums and Art Galleries', NULL, NULL, NULL, NULL),
('116', 8420, 'Botanical and Zoological Gardens', NULL, NULL, NULL, NULL),
('124', 8610, 'Business Associations (Chamber of Commerce, trade associations, etc.)', NULL, NULL, NULL, NULL),
('124', 8620, 'Professional Organizations', NULL, NULL, NULL, NULL),
('124', 8630, 'Labor Organizations', NULL, NULL, NULL, NULL),
('124', 8640, 'Civic, Social and Fraternal Organizations (veterans, youth & civil groups, homeowners)', NULL, NULL, NULL, NULL),
('123', 8710, 'Engineering and Architectural Services', NULL, NULL, NULL, NULL),
('123', 8720, 'Accounting and Auditing and Bookkeeping', NULL, NULL, NULL, NULL),
('123', 8730, 'Research and Testing Services (including market research)', NULL, NULL, NULL, NULL),
('123', 8740, 'Consulting Services', NULL, NULL, NULL, NULL),
('123', 8750, 'Motivational/Educational Seminars', NULL, NULL, NULL, NULL),
('123', 8760, 'Management and Public Relations', NULL, NULL, NULL, NULL),
('126', 8810, 'Private Household', NULL, NULL, NULL, NULL),
('123', 8999, 'Services - not listed above', NULL, NULL, NULL, NULL),
('125', 9000, 'Executive, Legislative and General', NULL, NULL, NULL, NULL),
('127', 9100, 'Bingo Supply', NULL, NULL, NULL, NULL),
('127', 9110, 'Bingo Equipment/Software', NULL, NULL, NULL, NULL),
('127', 9120, 'Keno Supplies/Hardware', NULL, NULL, NULL, NULL),
('127', 9130, 'Slot Machine Equipment/Software/Supply', NULL, NULL, NULL, NULL),
('127', 9140, 'Table Games Equipment/Software/Supply', NULL, NULL, NULL, NULL),
('127', 9150, 'Casino Computer Hardware/Software/Supply', NULL, NULL, NULL, NULL),
('127', 9160, 'Casino Gage Management Equipment', NULL, NULL, NULL, NULL),
('127', 9170, 'Casino Management Consulting/Professional Services', NULL, NULL, NULL, NULL),
('127', 9180, 'Casino Hotel Equipment/Supply', NULL, NULL, NULL, NULL),
('127', 9190, 'Casino Tobacco Supplier', NULL, NULL, NULL, NULL),
('127', 9200, 'Casino Food & Beverage Suppliers', NULL, NULL, NULL, NULL),
('127', 9210, 'Casino Liquor Supplier', NULL, NULL, NULL, NULL),
('127', 9220, 'Casino Tobacco Supplier', NULL, NULL, NULL, NULL),
('127', 9230, 'Casino Retail/Gift Shop Supplier', NULL, NULL, NULL, NULL),
('127', 9240, 'Casino/Gaming - not listed above', NULL, NULL, NULL, NULL),
('126', 9910, 'Estate or Trust', NULL, NULL, NULL, NULL);